import "@/styles/globals.css";

import { Maven_Pro } from "next/font/google";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/header";

const fontMaven = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-maven",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontMaven.variable,
        )}
      >
        <TRPCReactProvider>
          <div className="mx-auto max-w-screen-xl">
            <Header />
            {children}
          </div>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
